const root=document.documentElement, header=document.querySelector('.site-header'), progress=document.getElementById('progress'), backTop=document.getElementById('backTop'), menuBtn=document.getElementById('menuBtn'), navLinks=document.getElementById('navLinks'), themeBtn=document.getElementById('themeBtn');
const saved=localStorage.getItem('theme'); if(saved) root.dataset.theme=saved;
themeBtn.addEventListener('click',()=>{const next=root.dataset.theme==='dark'?'light':'dark';root.dataset.theme=next;localStorage.setItem('theme',next)});
menuBtn.addEventListener('click',()=>{const open=navLinks.classList.toggle('open');menuBtn.setAttribute('aria-expanded',open)});
document.querySelectorAll('.nav-links a').forEach(a=>a.addEventListener('click',()=>navLinks.classList.remove('open')));
window.addEventListener('scroll',()=>{const y=window.scrollY, max=document.documentElement.scrollHeight-innerHeight;progress.style.width=`${max?y/max*100:0}%`;header.classList.toggle('scrolled',y>20);backTop.classList.toggle('show',y>500)});
backTop.addEventListener('click',()=>scrollTo({top:0,behavior:'smooth'}));
const io=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>io.observe(el));
const counter=document.querySelector('.counter');let counted=false;new IntersectionObserver(([e])=>{if(e.isIntersecting&&!counted){counted=true;let n=0;const t=setInterval(()=>{n++;counter.textContent=n;if(n>=Number(counter.dataset.target))clearInterval(t)},120)}},{threshold:.5}).observe(counter);
document.getElementById('year').textContent=new Date().getFullYear();
document.getElementById('contactForm').addEventListener('submit',e=>{e.preventDefault();const d=new FormData(e.currentTarget),subject=encodeURIComponent(d.get('subject')),body=encodeURIComponent(`Name: ${d.get('name')}\nEmail: ${d.get('email')}\n\n${d.get('message')}`);location.href=`mailto:farhan.acc365@gmail.com?subject=${subject}&body=${body}`});
